### ISSUE TITLE
bspkrsCore + LiteLoader crash

### ISSUE THREAD

**Issue by Sir-Will** [bspkrs-mods/bspkrsCore#15]
hey,

if I use your core mod with the liteloader + voxelmenu and I create a singleplayer world it crashes with this report:

http://pastebin.com/4baHBRNu

Here the log if you need it: http://pastebin.com/6XDQ7quM

If you need any other information let me know.

**Comment by kerwanstar** [comment]
I had this problem, too. Found your post while searching for a solution. I never found one, but while screwing around with the bspkrsCore config, I found that changing "showMainMenuMobs" to false seemed to fix the issue (at least, it worked for me).

**Comment by MichaelHillcox** [comment]
bspkrsCore isn't made for LiteLoader?
