### ISSUE TITLE
Weather 2 mod Crash

### ISSUE THREAD

**Issue by K4N0** [bspkrs-mods/bspkrsCore#35]
The mods run fine separate.
Crash when running these 3 mods together.
[1.7.10]bspkrsCore-universal-6.16
coroutil-1.7.10-1.1.6
weather2-1.7.10-2.3.17
http://pastebin.com/TCeFAL7u
Left an issue with Weather 2 mod as well
https://github.com/Corosauce/weather2/issues/126

**Comment by MichaelHillcox** [comment]
This doesn't seem to be our issue.
