### ISSUE TITLE
I've added Universal File and it still doesn't work

### ISSUE THREAD

**Issue by OliverMC2008** [bspkrs-mods/bspkrsCore#41]
![error1](https://user-images.githubusercontent.com/44544503/47614754-a868e480-da9c-11e8-9720-5869bee9991d.PNG)
Proof to show i have the universal file.
![error1addition](https://user-images.githubusercontent.com/44544503/47614760-cb939400-da9c-11e8-97d3-bef62afe1c53.PNG)
Please help me, thanks

**Comment by MichaelHillcox** [comment]
You've got two of the same jars in the same dir but I'm sure you've dealt with this by now
